name: learn-github-action
run-name: ${{ github.actor }} is trigger github action
on:
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: npm install
        run: npm i

      - name: npm run lint
        run: npm run lint

      - name: npm run build
        run: npm run build:ci
