name: learn-github-action
run-name: ${{ github.actor }} is trigger github action
on:
  - pull_request
jobs:
  job-one:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup node version
      - uses: actions/setup-node@3
        with:
          node-version: "18"

      - name: npm install
      - run: npm i

      - name: npm run lint
      - run: npm run lint

      - name: npm run build
      - run: npm run build:ci
